// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsersByOrganizationParams creates a new GetUsersByOrganizationParams object
// with the default values initialized.
func NewGetUsersByOrganizationParams() *GetUsersByOrganizationParams {
	var ()
	return &GetUsersByOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersByOrganizationParamsWithTimeout creates a new GetUsersByOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersByOrganizationParamsWithTimeout(timeout time.Duration) *GetUsersByOrganizationParams {
	var ()
	return &GetUsersByOrganizationParams{

		timeout: timeout,
	}
}

// NewGetUsersByOrganizationParamsWithContext creates a new GetUsersByOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersByOrganizationParamsWithContext(ctx context.Context) *GetUsersByOrganizationParams {
	var ()
	return &GetUsersByOrganizationParams{

		Context: ctx,
	}
}

// NewGetUsersByOrganizationParamsWithHTTPClient creates a new GetUsersByOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersByOrganizationParamsWithHTTPClient(client *http.Client) *GetUsersByOrganizationParams {
	var ()
	return &GetUsersByOrganizationParams{
		HTTPClient: client,
	}
}

/*GetUsersByOrganizationParams contains all the parameters to send to the API endpoint
for the get users by organization operation typically these are written to a http.Request
*/
type GetUsersByOrganizationParams struct {

	/*ID
	  ID of organization

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users by organization params
func (o *GetUsersByOrganizationParams) WithTimeout(timeout time.Duration) *GetUsersByOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users by organization params
func (o *GetUsersByOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users by organization params
func (o *GetUsersByOrganizationParams) WithContext(ctx context.Context) *GetUsersByOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users by organization params
func (o *GetUsersByOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users by organization params
func (o *GetUsersByOrganizationParams) WithHTTPClient(client *http.Client) *GetUsersByOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users by organization params
func (o *GetUsersByOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get users by organization params
func (o *GetUsersByOrganizationParams) WithID(id int32) *GetUsersByOrganizationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get users by organization params
func (o *GetUsersByOrganizationParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersByOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
