// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/organization-goclient/models"
)

// GetPlanReader is a Reader for the GetPlan structure.
type GetPlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetPlanUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetPlanForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetPlanDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPlanOK creates a GetPlanOK with default headers values
func NewGetPlanOK() *GetPlanOK {
	return &GetPlanOK{}
}

/*GetPlanOK handles this case with default header values.

Successfully returned the plan
*/
type GetPlanOK struct {
	Payload *models.Plan
}

func (o *GetPlanOK) Error() string {
	return fmt.Sprintf("[GET /plans/{id}][%d] getPlanOK  %+v", 200, o.Payload)
}

func (o *GetPlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Plan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlanUnauthorized creates a GetPlanUnauthorized with default headers values
func NewGetPlanUnauthorized() *GetPlanUnauthorized {
	return &GetPlanUnauthorized{}
}

/*GetPlanUnauthorized handles this case with default header values.

Not authorized
*/
type GetPlanUnauthorized struct {
}

func (o *GetPlanUnauthorized) Error() string {
	return fmt.Sprintf("[GET /plans/{id}][%d] getPlanUnauthorized ", 401)
}

func (o *GetPlanUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPlanForbidden creates a GetPlanForbidden with default headers values
func NewGetPlanForbidden() *GetPlanForbidden {
	return &GetPlanForbidden{}
}

/*GetPlanForbidden handles this case with default header values.

Forbidden
*/
type GetPlanForbidden struct {
}

func (o *GetPlanForbidden) Error() string {
	return fmt.Sprintf("[GET /plans/{id}][%d] getPlanForbidden ", 403)
}

func (o *GetPlanForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPlanDefault creates a GetPlanDefault with default headers values
func NewGetPlanDefault(code int) *GetPlanDefault {
	return &GetPlanDefault{
		_statusCode: code,
	}
}

/*GetPlanDefault handles this case with default header values.

unexpected error
*/
type GetPlanDefault struct {
	_statusCode int
}

// Code gets the status code for the get plan default response
func (o *GetPlanDefault) Code() int {
	return o._statusCode
}

func (o *GetPlanDefault) Error() string {
	return fmt.Sprintf("[GET /plans/{id}][%d] getPlan default ", o._statusCode)
}

func (o *GetPlanDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
