// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/organization-goclient/models"
)

// GetOrganizationsReader is a Reader for the GetOrganizations structure.
type GetOrganizationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOrganizationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetOrganizationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetOrganizationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetOrganizationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOrganizationsOK creates a GetOrganizationsOK with default headers values
func NewGetOrganizationsOK() *GetOrganizationsOK {
	return &GetOrganizationsOK{}
}

/*GetOrganizationsOK handles this case with default header values.

Successfully returned the list of items
*/
type GetOrganizationsOK struct {
	Payload []*models.Organization
}

func (o *GetOrganizationsOK) Error() string {
	return fmt.Sprintf("[GET /organizations][%d] getOrganizationsOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationsUnauthorized creates a GetOrganizationsUnauthorized with default headers values
func NewGetOrganizationsUnauthorized() *GetOrganizationsUnauthorized {
	return &GetOrganizationsUnauthorized{}
}

/*GetOrganizationsUnauthorized handles this case with default header values.

Not authorized
*/
type GetOrganizationsUnauthorized struct {
}

func (o *GetOrganizationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /organizations][%d] getOrganizationsUnauthorized ", 401)
}

func (o *GetOrganizationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationsForbidden creates a GetOrganizationsForbidden with default headers values
func NewGetOrganizationsForbidden() *GetOrganizationsForbidden {
	return &GetOrganizationsForbidden{}
}

/*GetOrganizationsForbidden handles this case with default header values.

Forbidden
*/
type GetOrganizationsForbidden struct {
}

func (o *GetOrganizationsForbidden) Error() string {
	return fmt.Sprintf("[GET /organizations][%d] getOrganizationsForbidden ", 403)
}

func (o *GetOrganizationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationsDefault creates a GetOrganizationsDefault with default headers values
func NewGetOrganizationsDefault(code int) *GetOrganizationsDefault {
	return &GetOrganizationsDefault{
		_statusCode: code,
	}
}

/*GetOrganizationsDefault handles this case with default header values.

unexpected error
*/
type GetOrganizationsDefault struct {
	_statusCode int
}

// Code gets the status code for the get organizations default response
func (o *GetOrganizationsDefault) Code() int {
	return o._statusCode
}

func (o *GetOrganizationsDefault) Error() string {
	return fmt.Sprintf("[GET /organizations][%d] getOrganizations default ", o._statusCode)
}

func (o *GetOrganizationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
