package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsersInOrganizationParams creates a new GetUsersInOrganizationParams object
// with the default values initialized.
func NewGetUsersInOrganizationParams() *GetUsersInOrganizationParams {
	var ()
	return &GetUsersInOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersInOrganizationParamsWithTimeout creates a new GetUsersInOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersInOrganizationParamsWithTimeout(timeout time.Duration) *GetUsersInOrganizationParams {
	var ()
	return &GetUsersInOrganizationParams{

		timeout: timeout,
	}
}

// NewGetUsersInOrganizationParamsWithContext creates a new GetUsersInOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersInOrganizationParamsWithContext(ctx context.Context) *GetUsersInOrganizationParams {
	var ()
	return &GetUsersInOrganizationParams{

		Context: ctx,
	}
}

/*GetUsersInOrganizationParams contains all the parameters to send to the API endpoint
for the get users in organization operation typically these are written to a http.Request
*/
type GetUsersInOrganizationParams struct {

	/*Filter
	  Filter objects based on fields in the object.  E.g. filter=name:my-simulation,state:running

	*/
	Filter *string
	/*ID
	  ID of organization to fetch users for

	*/
	ID int64
	/*Limit
	  number of items to return within the query

	*/
	Limit *int64
	/*Offset
	  starting paging count; ex. 60 will skip the first 60 items in the list

	*/
	Offset *int64
	/*Sort
	  key:direction pairs for one or multiple field sort orders

	*/
	Sort []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users in organization params
func (o *GetUsersInOrganizationParams) WithTimeout(timeout time.Duration) *GetUsersInOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users in organization params
func (o *GetUsersInOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users in organization params
func (o *GetUsersInOrganizationParams) WithContext(ctx context.Context) *GetUsersInOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users in organization params
func (o *GetUsersInOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithFilter adds the filter to the get users in organization params
func (o *GetUsersInOrganizationParams) WithFilter(filter *string) *GetUsersInOrganizationParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the get users in organization params
func (o *GetUsersInOrganizationParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithID adds the id to the get users in organization params
func (o *GetUsersInOrganizationParams) WithID(id int64) *GetUsersInOrganizationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get users in organization params
func (o *GetUsersInOrganizationParams) SetID(id int64) {
	o.ID = id
}

// WithLimit adds the limit to the get users in organization params
func (o *GetUsersInOrganizationParams) WithLimit(limit *int64) *GetUsersInOrganizationParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get users in organization params
func (o *GetUsersInOrganizationParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get users in organization params
func (o *GetUsersInOrganizationParams) WithOffset(offset *int64) *GetUsersInOrganizationParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get users in organization params
func (o *GetUsersInOrganizationParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSort adds the sort to the get users in organization params
func (o *GetUsersInOrganizationParams) WithSort(sort []string) *GetUsersInOrganizationParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get users in organization params
func (o *GetUsersInOrganizationParams) SetSort(sort []string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersInOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesSort := o.Sort

	joinedSort := swag.JoinByFormat(valuesSort, "csv")
	// query array param sort
	if err := r.SetQueryParam("sort", joinedSort...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
