package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/organization-goclient/models"
)

// GetUsersInOrganizationReader is a Reader for the GetUsersInOrganization structure.
type GetUsersInOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersInOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersInOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetUsersInOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetUsersInOrganizationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetUsersInOrganizationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetUsersInOrganizationOK creates a GetUsersInOrganizationOK with default headers values
func NewGetUsersInOrganizationOK() *GetUsersInOrganizationOK {
	return &GetUsersInOrganizationOK{}
}

/*GetUsersInOrganizationOK handles this case with default header values.

Successfully returned the list of items
*/
type GetUsersInOrganizationOK struct {
	Payload []*models.User
}

func (o *GetUsersInOrganizationOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{id}/users][%d] getUsersInOrganizationOK  %+v", 200, o.Payload)
}

func (o *GetUsersInOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersInOrganizationUnauthorized creates a GetUsersInOrganizationUnauthorized with default headers values
func NewGetUsersInOrganizationUnauthorized() *GetUsersInOrganizationUnauthorized {
	return &GetUsersInOrganizationUnauthorized{}
}

/*GetUsersInOrganizationUnauthorized handles this case with default header values.

Not authorized
*/
type GetUsersInOrganizationUnauthorized struct {
	Payload *models.Error
}

func (o *GetUsersInOrganizationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /organizations/{id}/users][%d] getUsersInOrganizationUnauthorized  %+v", 401, o.Payload)
}

func (o *GetUsersInOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersInOrganizationForbidden creates a GetUsersInOrganizationForbidden with default headers values
func NewGetUsersInOrganizationForbidden() *GetUsersInOrganizationForbidden {
	return &GetUsersInOrganizationForbidden{}
}

/*GetUsersInOrganizationForbidden handles this case with default header values.

Forbidden
*/
type GetUsersInOrganizationForbidden struct {
	Payload *models.Error
}

func (o *GetUsersInOrganizationForbidden) Error() string {
	return fmt.Sprintf("[GET /organizations/{id}/users][%d] getUsersInOrganizationForbidden  %+v", 403, o.Payload)
}

func (o *GetUsersInOrganizationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersInOrganizationDefault creates a GetUsersInOrganizationDefault with default headers values
func NewGetUsersInOrganizationDefault(code int) *GetUsersInOrganizationDefault {
	return &GetUsersInOrganizationDefault{
		_statusCode: code,
	}
}

/*GetUsersInOrganizationDefault handles this case with default header values.

unexpected error
*/
type GetUsersInOrganizationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get users in organization default response
func (o *GetUsersInOrganizationDefault) Code() int {
	return o._statusCode
}

func (o *GetUsersInOrganizationDefault) Error() string {
	return fmt.Sprintf("[GET /organizations/{id}/users][%d] getUsersInOrganization default  %+v", o._statusCode, o.Payload)
}

func (o *GetUsersInOrganizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
