package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImpersonateURLForUserParams creates a new GetImpersonateURLForUserParams object
// with the default values initialized.
func NewGetImpersonateURLForUserParams() *GetImpersonateURLForUserParams {
	var ()
	return &GetImpersonateURLForUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImpersonateURLForUserParamsWithTimeout creates a new GetImpersonateURLForUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImpersonateURLForUserParamsWithTimeout(timeout time.Duration) *GetImpersonateURLForUserParams {
	var ()
	return &GetImpersonateURLForUserParams{

		timeout: timeout,
	}
}

// NewGetImpersonateURLForUserParamsWithContext creates a new GetImpersonateURLForUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImpersonateURLForUserParamsWithContext(ctx context.Context) *GetImpersonateURLForUserParams {
	var ()
	return &GetImpersonateURLForUserParams{

		Context: ctx,
	}
}

/*GetImpersonateURLForUserParams contains all the parameters to send to the API endpoint
for the get impersonate URL for user operation typically these are written to a http.Request
*/
type GetImpersonateURLForUserParams struct {

	/*ID
	  ID of user to impersonate

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get impersonate URL for user params
func (o *GetImpersonateURLForUserParams) WithTimeout(timeout time.Duration) *GetImpersonateURLForUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get impersonate URL for user params
func (o *GetImpersonateURLForUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get impersonate URL for user params
func (o *GetImpersonateURLForUserParams) WithContext(ctx context.Context) *GetImpersonateURLForUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get impersonate URL for user params
func (o *GetImpersonateURLForUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the get impersonate URL for user params
func (o *GetImpersonateURLForUserParams) WithID(id string) *GetImpersonateURLForUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get impersonate URL for user params
func (o *GetImpersonateURLForUserParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetImpersonateURLForUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
