package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/organization-goclient/models"
)

// PostOrganizationsReader is a Reader for the PostOrganizations structure.
type PostOrganizationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOrganizationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostOrganizationsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostOrganizationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostOrganizationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostOrganizationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostOrganizationsCreated creates a PostOrganizationsCreated with default headers values
func NewPostOrganizationsCreated() *PostOrganizationsCreated {
	return &PostOrganizationsCreated{}
}

/*PostOrganizationsCreated handles this case with default header values.

Successfully created the organization
*/
type PostOrganizationsCreated struct {
	Payload *models.Organization
}

func (o *PostOrganizationsCreated) Error() string {
	return fmt.Sprintf("[POST /organizations][%d] postOrganizationsCreated  %+v", 201, o.Payload)
}

func (o *PostOrganizationsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Organization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganizationsUnauthorized creates a PostOrganizationsUnauthorized with default headers values
func NewPostOrganizationsUnauthorized() *PostOrganizationsUnauthorized {
	return &PostOrganizationsUnauthorized{}
}

/*PostOrganizationsUnauthorized handles this case with default header values.

Not authorized
*/
type PostOrganizationsUnauthorized struct {
	Payload *models.Error
}

func (o *PostOrganizationsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /organizations][%d] postOrganizationsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostOrganizationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganizationsForbidden creates a PostOrganizationsForbidden with default headers values
func NewPostOrganizationsForbidden() *PostOrganizationsForbidden {
	return &PostOrganizationsForbidden{}
}

/*PostOrganizationsForbidden handles this case with default header values.

Forbidden
*/
type PostOrganizationsForbidden struct {
	Payload *models.Error
}

func (o *PostOrganizationsForbidden) Error() string {
	return fmt.Sprintf("[POST /organizations][%d] postOrganizationsForbidden  %+v", 403, o.Payload)
}

func (o *PostOrganizationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganizationsDefault creates a PostOrganizationsDefault with default headers values
func NewPostOrganizationsDefault(code int) *PostOrganizationsDefault {
	return &PostOrganizationsDefault{
		_statusCode: code,
	}
}

/*PostOrganizationsDefault handles this case with default header values.

error
*/
type PostOrganizationsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post organizations default response
func (o *PostOrganizationsDefault) Code() int {
	return o._statusCode
}

func (o *PostOrganizationsDefault) Error() string {
	return fmt.Sprintf("[POST /organizations][%d] PostOrganizations default  %+v", o._statusCode, o.Payload)
}

func (o *PostOrganizationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
