package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/organization-goclient/models"
)

// NewPostOrganizationsParams creates a new PostOrganizationsParams object
// with the default values initialized.
func NewPostOrganizationsParams() *PostOrganizationsParams {
	var ()
	return &PostOrganizationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationsParamsWithTimeout creates a new PostOrganizationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOrganizationsParamsWithTimeout(timeout time.Duration) *PostOrganizationsParams {
	var ()
	return &PostOrganizationsParams{

		timeout: timeout,
	}
}

// NewPostOrganizationsParamsWithContext creates a new PostOrganizationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostOrganizationsParamsWithContext(ctx context.Context) *PostOrganizationsParams {
	var ()
	return &PostOrganizationsParams{

		Context: ctx,
	}
}

/*PostOrganizationsParams contains all the parameters to send to the API endpoint
for the post organizations operation typically these are written to a http.Request
*/
type PostOrganizationsParams struct {

	/*Organization*/
	Organization *models.Organization

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post organizations params
func (o *PostOrganizationsParams) WithTimeout(timeout time.Duration) *PostOrganizationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organizations params
func (o *PostOrganizationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organizations params
func (o *PostOrganizationsParams) WithContext(ctx context.Context) *PostOrganizationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organizations params
func (o *PostOrganizationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithOrganization adds the organization to the post organizations params
func (o *PostOrganizationsParams) WithOrganization(organization *models.Organization) *PostOrganizationsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post organizations params
func (o *PostOrganizationsParams) SetOrganization(organization *models.Organization) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Organization == nil {
		o.Organization = new(models.Organization)
	}

	if err := r.SetBodyParam(o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
