package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ImpersonateURL impersonate URL
// swagger:model impersonateURL
type ImpersonateURL struct {

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this impersonate URL
func (m *ImpersonateURL) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
